services:
  codec_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: thangved/zlib-codec-server
    container_name: zlib-codec-server
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - KEY_ID=1234567890
      - METADATA_ENCODING_ENCRYPTED=binary/encrypted
      - METADATA_ENCRYPTION_KEY_ID=1234567890
