services:
  codec_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/thangved/zlib-codec-server:main
    container_name: zlib-codec-server
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - KEY_ID=1234567890
